### ISSUE TITLE
Webpack config can lead to CSP errors

### ISSUE THREAD

**Issue by jackmac92** [SimonAlling/userscripter#30]
I was running into CSP errors on github, realized there were some `eval` statements in the bundled code. For some reason setting `devtool: 'inline-source-map'` fixes that. https://github.com/webpack/webpack/issues/4899#issuecomment-609724897

I'll send a PR if you'd like

**Comment by SimonAlling** [comment]
Thanks for reporting this issue (which I just noticed)! Do you encounter this problem even with `USERSCRIPTER_MODE` set to `production`. Example command:

```
USERSCRIPTER_MODE=production npm run build
```

**Comment by jackmac92** [comment]
@SimonAlling sorry I missed this earlier, setting that env var does fix the problem!

Would it make sense to default to production mode?

**Comment by SimonAlling** [comment]
@jackmac92: I don't know, but I do know that this has to be fixed somehow; I can easily imagine just how frustrating it would be to have to deal with `eval` CSP errors when one just wanted to build a userscript. Definitely not acceptable.

**Comment by SimonAlling** [comment]
Could you perhaps share a sample userscript that I can use to verify that I have found a fix?

**Comment by jackmac92** [comment]
@SimonAlling awesome! Happy to test it out if that would help verify

**Comment by SimonAlling** [comment]
I have proposed a fix in #35. Please let me know if it solves the problem, @jackmac92.

**Comment by SimonAlling** [comment]
I'm going to merge the fix and consider this resolved. Please reopen otherwise. :slightly_smiling_face:
