### ISSUE TITLE
Conventional Commits should be enforced

### ISSUE THREAD

**Issue by SimonAlling** [SimonAlling/userscripter#44]
#38 made me decide to start using Conventional Commits, but I know how it's gonna end up if it's not enforced in CI …

**Comment by avallete** [comment]
I think the best way to "enforce" those commits is 2 steps checks:

1. Locally enforce and configure commit convention, allowing contributors to fail quickly (and avoid the need to rewrite a remote PR history). That can be done pretty easily with [husky](https://github.com/typicode/husky) and [commitlint](https://github.com/conventional-changelog/commitlint)
2. Add benefits to the fact of following this convention. The primary advantage of this convention, besides uniformization, is the ability to automate release versions. Using [semantic-release](https://github.com/semantic-release/semantic-release), we could add ContinousDeployment on top of the CI. Automatically releasing a new version of the package if needed when new commits are pushed into `master`.

This workflow both enforce (bad release version or not release at all if not followed) and draw maximum benefits from conventional commits convention.

I have set up this workflow on this repo [userscripter-boilerplate](https://github.com/avallete/userscripter-boilerplate) and could help set up the same one here if needed.

**Comment by SimonAlling** [comment]
Yes, especially Husky hooks are a given, and also a GitHub Actions check. Continuous deployment _may_ happen at some point in the future, but I think we should move in that direction with small steps.
